/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTrophy: typeof import('./src/components/AddTrophy.vue')['default']
    DButton: typeof import('vue-devui/button/index.es.js')['Button']
    DCheckbox: typeof import('vue-devui/checkbox/index.es.js')['Checkbox']
    DCheckboxGroup: typeof import('vue-devui/checkbox-group/index.es.js')['CheckboxGroup']
    DColumn: typeof import('vue-devui/table/index.es.js')['Column']
    DForm: typeof import('vue-devui/form/index.es.js')['Form']
    DFormControl: typeof import('vue-devui/form-control/index.es.js')['FormControl']
    DFormItem: typeof import('vue-devui/form/index.es.js')['FormItem']
    DFormLabel: typeof import('vue-devui/form-label/index.es.js')['FormLabel']
    DFormOperation: typeof import('vue-devui/form-operation/index.es.js')['FormOperation']
    DInput: typeof import('vue-devui/input/index.es.js')['Input']
    DRadio: typeof import('vue-devui/radio/index.es.js')['Radio']
    DSelect: typeof import('vue-devui/select/index.es.js')['Select']
    DSwitch: typeof import('vue-devui/switch/index.es.js')['Switch']
    DTable: typeof import('vue-devui/table/index.es.js')['Table']
    DTagInput: typeof import('vue-devui/tag-input/index.es.js')['TagInput']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongList: typeof import('./src/components/SongList.vue')['default']
    TrophyList: typeof import('./src/components/TrophyList.vue')['default']
  }
}
